DIAGRAM.set_name('Плановое отключение потребителей')
p_res, (res, crew) = DIAGRAM.add_pool(ROOT_PROCESS_ID, ['РЭС', 'Бригада РЭС'])
p_cus, (cus,) = DIAGRAM.add_pool(ROOT_PROCESS_ID, ['ЦУС'])
p_sales, (sales,) = DIAGRAM.add_pool(ROOT_PROCESS_ID, ['Энергосбытовая компания'])

send = DIAGRAM.add_user_task('Направить заявку на отключение', res)
review = DIAGRAM.add_user_task('Рассмотреть заявку', cus)
ok = DIAGRAM.add_exclusive_gateway('Согласовать заявку?', cus)
reject = DIAGRAM.add_user_task('Направить отказ', cus)
accept = DIAGRAM.add_user_task('Направить согласование', cus)
decision = DIAGRAM.add_user_task('Получить решение ЦУС', res)
approved = DIAGRAM.add_exclusive_gateway('Заявка согласована?', res)
who = DIAGRAM.add_inclusive_gateway('Кого уведомить?', res)
social = DIAGRAM.add_user_task('Уведомить социальные объекты с подтверждением', res)
legal = DIAGRAM.add_user_task('Направить письма юрлицам', res)
site = DIAGRAM.add_script_task('Оповестить население на сайте', res)
notified = DIAGRAM.add_inclusive_gateway('', res)
inform_sales = DIAGRAM.add_user_task('Передать информацию в энергосбыт', res)
publish = DIAGRAM.add_user_task('Разместить информацию в контакт-центре', sales)
switch_off = DIAGRAM.add_user_task('Выполнить отключение и работы', crew)
switch_on = DIAGRAM.add_user_task('Включить потребителей', crew)
close = DIAGRAM.add_user_task('Сообщить о закрытии заявки', res)
closed = DIAGRAM.add_user_task('Закрыть заявку', cus)

DIAGRAM.add_link(ROOT_START_TASK_ID, send)
DIAGRAM.add_link(send, review)
DIAGRAM.add_link(send, decision)
DIAGRAM.add_link(review, ok)
DIAGRAM.add_link(ok, reject, name='нет')
DIAGRAM.add_link(ok, accept, name='да')
DIAGRAM.add_link(reject, decision)
DIAGRAM.add_link(accept, decision)
DIAGRAM.add_link(decision, approved)
DIAGRAM.add_link(approved, ROOT_END_TASK_ID, name='нет')
DIAGRAM.add_link(approved, who, name='да')
DIAGRAM.add_link(who, social, name='есть соцобъекты')
DIAGRAM.add_link(who, legal, name='есть юрлица')
DIAGRAM.add_link(who, site, name='всегда')
DIAGRAM.add_link(social, notified)
DIAGRAM.add_link(legal, notified)
DIAGRAM.add_link(site, notified)
DIAGRAM.add_link(notified, inform_sales)
DIAGRAM.add_link(inform_sales, publish)
DIAGRAM.add_link(inform_sales, switch_off)
DIAGRAM.add_link(switch_off, switch_on)
DIAGRAM.add_link(switch_on, close)
DIAGRAM.add_link(close, closed)
