DIAGRAM.set_name('Согласование инвестиционного проекта')
pool, (initiator, tech, econ, lawyer, committee) = DIAGRAM.add_pool(ROOT_PROCESS_ID, ['Инициатор', 'Технический эксперт', 'Экономист', 'Юрист', 'Инвестиционный комитет'])

prepare = DIAGRAM.add_user_task('Подготовить паспорт и финмодель', initiator)
passport = DIAGRAM.add_data_object('Паспорт проекта и финмодель', initiator)
tech_review = DIAGRAM.add_user_task('Провести техническую экспертизу', tech)
tech_ok = DIAGRAM.add_exclusive_gateway('Замечания эксперта?', tech)
econ_review = DIAGRAM.add_user_task('Провести экономическую экспертизу', econ)
econ_ok = DIAGRAM.add_exclusive_gateway('Замечания экономиста?', econ)
rework = DIAGRAM.add_user_task('Доработать проект', initiator)
legal = DIAGRAM.add_user_task('Подготовить заключение по рискам закупки', lawyer)
opinion = DIAGRAM.add_data_object('Заключение юриста', lawyer)
decide = DIAGRAM.add_user_task('Принять решение о включении в инвестпрограмму', committee)
minutes = DIAGRAM.add_data_object('Протокол комитета', committee)
included = DIAGRAM.add_exclusive_gateway('Проект включён?', committee)
notify = DIAGRAM.add_script_task('Уведомить инициатора', committee)
procurement = DIAGRAM.add_user_task('Начать подготовку к закупке', initiator)
archive = DIAGRAM.add_script_task('Архивировать проект', committee)

DIAGRAM.add_link(ROOT_START_TASK_ID, prepare)
DIAGRAM.add_link(prepare, passport)
DIAGRAM.add_link(passport, tech_review)
DIAGRAM.add_link(prepare, tech_review)
DIAGRAM.add_link(tech_review, tech_ok)
DIAGRAM.add_link(tech_ok, rework, name='есть')
DIAGRAM.add_link(tech_ok, econ_review, name='нет')
DIAGRAM.add_link(econ_review, econ_ok)
DIAGRAM.add_link(econ_ok, rework, name='есть')
DIAGRAM.add_link(econ_ok, legal, name='нет')
DIAGRAM.add_link(rework, tech_review)
DIAGRAM.add_link(legal, opinion)
DIAGRAM.add_link(opinion, decide)
DIAGRAM.add_link(legal, decide)
DIAGRAM.add_link(decide, minutes)
DIAGRAM.add_link(minutes, notify)
DIAGRAM.add_link(decide, included)
DIAGRAM.add_link(included, notify, name='да')
DIAGRAM.add_link(included, archive, name='нет')
DIAGRAM.add_link(notify, procurement)
DIAGRAM.add_link(procurement, ROOT_END_TASK_ID)
DIAGRAM.add_link(archive, ROOT_END_TASK_ID)
