pool, (dispatcher, master, brigade) = DIAGRAM.add_pool(ROOT_PROCESS_ID, ['Диспетчер', 'Мастер участка', 'Бригада'])
receive = DIAGRAM.add_user_task('Получить заявку и зарегистрировать в журнале', dispatcher)
evaluate = DIAGRAM.add_user_task('Оценить неисправность', master)
decision = DIAGRAM.add_exclusive_gateway('Требуется отключение оборудования?', master)
approve = DIAGRAM.add_user_task('Согласовать вывод оборудования в ремонт', dispatcher)
assign = DIAGRAM.add_user_task('Назначить бригаду', master)
split = DIAGRAM.add_parallel_gateway('', master)
prepare = DIAGRAM.add_user_task('Подготовить материалы и инструменты', brigade)
permit = DIAGRAM.add_user_task('Оформить наряд‑допуск', master)
join = DIAGRAM.add_parallel_gateway('', master)
repair = DIAGRAM.add_user_task('Выполнить ремонт', brigade)
report = DIAGRAM.add_user_task('Докладывать о завершении', brigade)
close = DIAGRAM.add_user_task('Закрыть заявку', dispatcher)
DIAGRAM.add_link(ROOT_START_TASK_ID, receive)
DIAGRAM.add_link(receive, evaluate)
DIAGRAM.add_link(evaluate, decision)
DIAGRAM.add_link(decision, approve, name='да')
DIAGRAM.add_link(decision, assign, name='нет')
DIAGRAM.add_link(approve, split)
DIAGRAM.add_link(assign, split)
DIAGRAM.add_link(split, prepare)
DIAGRAM.add_link(split, permit)
DIAGRAM.add_link(prepare, join)
DIAGRAM.add_link(permit, join)
DIAGRAM.add_link(join, repair)
DIAGRAM.add_link(repair, report)
DIAGRAM.add_link(report, close)
DIAGRAM.add_link(close, ROOT_END_TASK_ID)