pool, (region, cus, res, es, crew) = DIAGRAM.add_pool(ROOT_PROCESS_ID, ['Район сетей', 'ЦУС', 'РЭС', 'Энергосбытовая компания', 'Бригада'])

submit = DIAGRAM.add_user_task('Отправить заявку на отключение', region)
review = DIAGRAM.add_script_task('Рассмотреть заявку', cus)
decision = DIAGRAM.add_exclusive_gateway('Заявка одобрена?', cus)
reject = DIAGRAM.add_script_task('Отказать в заявке', cus)

split = DIAGRAM.add_parallel_gateway('', res)
notify_social = DIAGRAM.add_user_task('Уведомить социальные объекты', res)
notify_legal = DIAGRAM.add_user_task('Уведомить крупные юридические лица', res)
notify_public = DIAGRAM.add_user_task('Уведомить население через сайт', res)
join = DIAGRAM.add_parallel_gateway('', res)

inform_es = DIAGRAM.add_script_task('Передать информацию об отключении', res)
publish = DIAGRAM.add_script_task('Разместить информацию в контакт-центре', es)

work = DIAGRAM.add_user_task('Выполнить отключение и работы', crew)
restore = DIAGRAM.add_user_task('Выполнить включение', crew)

report = DIAGRAM.add_script_task('Сообщить о закрытии заявки', res)

DIAGRAM.add_link(ROOT_START_TASK_ID, submit)
DIAGRAM.add_link(submit, review)
DIAGRAM.add_link(review, decision)
DIAGRAM.add_link(decision, reject, name='нет')
DIAGRAM.add_link(reject, ROOT_END_TASK_ID)
DIAGRAM.add_link(decision, split, name='да')
DIAGRAM.add_link(split, notify_social)
DIAGRAM.add_link(split, notify_legal)
DIAGRAM.add_link(split, notify_public)
DIAGRAM.add_link(notify_social, join)
DIAGRAM.add_link(notify_legal, join)
DIAGRAM.add_link(notify_public, join)
DIAGRAM.add_link(join, inform_es)
DIAGRAM.add_link(inform_es, publish)
DIAGRAM.add_link(publish, work)
DIAGRAM.add_link(work, restore)
DIAGRAM.add_link(restore, report)
DIAGRAM.add_link(report, ROOT_END_TASK_ID)