DIAGRAM.set_name('Инцидент в АИИС КУЭ')
pool, (monitoring, line1, line2, contractor, metrologist) = DIAGRAM.add_pool(ROOT_PROCESS_ID, ['Система мониторинга', 'Первая линия', 'Вторая линия', 'Подрядчик связи', 'Инженер-метролог'])

source = DIAGRAM.add_exclusive_gateway('Кто обнаружил?', monitoring)
auto = DIAGRAM.add_script_task('Создать заявку автоматически', monitoring)
manual = DIAGRAM.add_user_task('Создать заявку по звонку', line1)
merge_in = DIAGRAM.add_exclusive_gateway('', line1)
kb = DIAGRAM.add_user_task('Решить по базе знаний', line1)
kb_base = DIAGRAM.add_data_store('База знаний', line1)
solved = DIAGRAM.add_exclusive_gateway('Решено за 30 минут?', line1)
diagnose = DIAGRAM.add_user_task('Диагностировать проблему', line2)
fork = DIAGRAM.add_parallel_gateway('', line2)
notify = DIAGRAM.add_script_task('Уведомить энергосбыт о неполных данных', line2)
cause = DIAGRAM.add_exclusive_gateway('Причина?', line2)
channel = DIAGRAM.add_user_task('Восстановить каналы связи', contractor)
device = DIAGRAM.add_user_task('Заменить или настроить оборудование', metrologist)
merge_fix = DIAGRAM.add_exclusive_gateway('', line2)
join = DIAGRAM.add_parallel_gateway('', line2)
recalc = DIAGRAM.add_script_task('Досчитать данные', line2)
merge_out = DIAGRAM.add_exclusive_gateway('', line2)
close = DIAGRAM.add_user_task('Закрыть заявку', line2)

DIAGRAM.add_link(ROOT_START_TASK_ID, source)
DIAGRAM.add_link(source, auto, name='мониторинг')
DIAGRAM.add_link(source, manual, name='звонок')
DIAGRAM.add_link(auto, merge_in)
DIAGRAM.add_link(manual, merge_in)
DIAGRAM.add_link(merge_in, kb)
DIAGRAM.add_link(kb_base, kb)
DIAGRAM.add_link(kb, solved)
DIAGRAM.add_link(solved, merge_out, name='да')
DIAGRAM.add_link(solved, diagnose, name='нет')
DIAGRAM.add_link(diagnose, fork)
DIAGRAM.add_link(fork, notify)
DIAGRAM.add_link(fork, cause)
DIAGRAM.add_link(cause, channel, name='каналы связи')
DIAGRAM.add_link(cause, device, name='оборудование')
DIAGRAM.add_link(channel, merge_fix)
DIAGRAM.add_link(device, merge_fix)
DIAGRAM.add_link(merge_fix, join)
DIAGRAM.add_link(notify, join)
DIAGRAM.add_link(join, recalc)
DIAGRAM.add_link(recalc, merge_out)
DIAGRAM.add_link(merge_out, close)
DIAGRAM.add_link(close, ROOT_END_TASK_ID)
