pool, (abonent, cabinet, billing, controller) = DIAGRAM.add_pool(ROOT_PROCESS_ID, ['Абонент', 'Личный кабинет', 'Биллинг', 'Контролёр'])

input_task = DIAGRAM.add_user_task('Ввести показания', abonent)
check_save = DIAGRAM.add_script_task('Проверить формат и сохранить', cabinet)
gateway_time = DIAGRAM.add_exclusive_gateway('Показания переданы до 25 числа?', cabinet)
avg_task = DIAGRAM.add_script_task('Вычислить среднее показание', billing)
gateway_suspicious = DIAGRAM.add_exclusive_gateway('Подозрительные показания?', billing)
controller_go = DIAGRAM.add_user_task('Выезд контролёра', controller)
capture = DIAGRAM.add_user_task('Снять фактические показания', controller)
report = DIAGRAM.add_user_task('Составить акт проверки', controller)
generate_invoice = DIAGRAM.add_script_task('Сформировать счёт', billing)
send_invoice = DIAGRAM.add_script_task('Отправить счёт в личный кабинет', cabinet)

DIAGRAM.add_link(ROOT_START_TASK_ID, input_task)
DIAGRAM.add_link(input_task, check_save)
DIAGRAM.add_link(check_save, gateway_time)
DIAGRAM.add_link(gateway_time, gateway_suspicious, name='да')
DIAGRAM.add_link(gateway_time, avg_task, name='нет')
DIAGRAM.add_link(avg_task, gateway_suspicious)
DIAGRAM.add_link(gateway_suspicious, generate_invoice, name='нет')
DIAGRAM.add_link(gateway_suspicious, controller_go, name='да')
DIAGRAM.add_link(controller_go, capture)
DIAGRAM.add_link(capture, report)
DIAGRAM.add_link(report, generate_invoice)
DIAGRAM.add_link(generate_invoice, send_invoice)
DIAGRAM.add_link(send_invoice, ROOT_END_TASK_ID)