DIAGRAM.set_name('Ликвидация аварии на распределительной сети')
pool, (scada, dispatcher, ovb, repair) = DIAGRAM.add_pool(ROOT_PROCESS_ID, ['SCADA', 'Диспетчер', 'Оперативно-выездная бригада', 'Ремонтная бригада'])

register = DIAGRAM.add_script_task('Зарегистрировать событие', scada)
alert = DIAGRAM.add_script_task('Оповестить диспетчера', scada)
assess = DIAGRAM.add_user_task('Оценить ситуацию', dispatcher)
dispatch = DIAGRAM.add_user_task('Направить бригаду', dispatcher)
travel = DIAGRAM.add_user_task('Выехать на место', ovb)
localize = DIAGRAM.create_subprocess('Локализовать повреждение', ovb)
inspect = DIAGRAM.add_user_task('Осмотреть участок', localize)
cut = DIAGRAM.add_user_task('Отключить повреждённый участок', localize)
ground = DIAGRAM.add_user_task('Установить заземления', localize)
backup = DIAGRAM.add_exclusive_gateway('Есть резервная схема?', ovb)
switch = DIAGRAM.add_user_task('Переключить на резервную схему', ovb)
call = DIAGRAM.add_user_task('Вызвать ремонтную бригаду', ovb)
fix = DIAGRAM.add_user_task('Устранить повреждение', repair)
merge = DIAGRAM.add_exclusive_gateway('', ovb)
check = DIAGRAM.add_user_task('Проверить питание', ovb)
restored = DIAGRAM.add_exclusive_gateway('Питание восстановлено?', ovb)
log_entry = DIAGRAM.add_user_task('Сделать запись в журнале', dispatcher)
journal = DIAGRAM.add_data_store('Оперативный журнал', dispatcher)
close = DIAGRAM.add_script_task('Закрыть событие', scada)

DIAGRAM.add_link(ROOT_START_TASK_ID, register)
DIAGRAM.add_link(register, alert)
DIAGRAM.add_link(alert, assess)
DIAGRAM.add_link(assess, dispatch)
DIAGRAM.add_link(dispatch, travel)
DIAGRAM.add_link(travel, localize)
DIAGRAM.add_link(inspect, cut)
DIAGRAM.add_link(cut, ground)
DIAGRAM.add_link(localize, backup)
DIAGRAM.add_link(backup, switch, name='да')
DIAGRAM.add_link(backup, call, name='нет')
DIAGRAM.add_link(call, fix)
DIAGRAM.add_link(switch, merge)
DIAGRAM.add_link(fix, merge)
DIAGRAM.add_link(merge, check)
DIAGRAM.add_link(check, restored)
DIAGRAM.add_link(restored, localize, name='нет')
DIAGRAM.add_link(restored, log_entry, name='да')
DIAGRAM.add_link(log_entry, journal)
DIAGRAM.add_link(log_entry, close)
DIAGRAM.add_link(close, ROOT_END_TASK_ID)
