DIAGRAM.set_name('Работы по наряду-допуску')
pool, (issuer, dispatcher, admitter, foreman) = DIAGRAM.add_pool(ROOT_PROCESS_ID, ['Выдающий наряд', 'Диспетчер', 'Допускающий', 'Производитель работ'])

draft = DIAGRAM.add_user_task('Оформить наряд-допуск', issuer)
permit = DIAGRAM.add_data_object('Наряд-допуск', issuer)
approve = DIAGRAM.add_user_task('Согласовать наряд', dispatcher)
approved = DIAGRAM.add_exclusive_gateway('Наряд согласован?', dispatcher)
fork = DIAGRAM.add_parallel_gateway('', admitter)
switch_off = DIAGRAM.add_user_task('Отключить оборудование', admitter)
posters = DIAGRAM.add_user_task('Вывесить плакаты', admitter)
grounding = DIAGRAM.add_user_task('Установить заземления', admitter)
join = DIAGRAM.add_parallel_gateway('', admitter)
check_place = DIAGRAM.add_user_task('Проверить рабочее место', admitter)
briefing = DIAGRAM.add_user_task('Провести целевой инструктаж', admitter)
admit = DIAGRAM.add_user_task('Допустить бригаду', admitter)
work = DIAGRAM.add_user_task('Выполнить работы', foreman)
hand_over = DIAGRAM.add_user_task('Сдать рабочее место', foreman)
close = DIAGRAM.add_user_task('Закрыть наряд', admitter)
report = DIAGRAM.add_user_task('Сообщить диспетчеру о завершении', admitter)

DIAGRAM.add_link(ROOT_START_TASK_ID, draft)
DIAGRAM.add_link(draft, permit)
DIAGRAM.add_link(draft, approve)
DIAGRAM.add_link(permit, approve)
DIAGRAM.add_link(approve, approved)
DIAGRAM.add_link(approved, draft, name='нет')
DIAGRAM.add_link(approved, fork, name='да')
DIAGRAM.add_link(fork, switch_off)
DIAGRAM.add_link(fork, posters)
DIAGRAM.add_link(fork, grounding)
DIAGRAM.add_link(switch_off, join)
DIAGRAM.add_link(posters, join)
DIAGRAM.add_link(grounding, join)
DIAGRAM.add_link(join, check_place)
DIAGRAM.add_link(check_place, briefing)
DIAGRAM.add_link(briefing, admit)
DIAGRAM.add_link(admit, work)
DIAGRAM.add_link(work, hand_over)
DIAGRAM.add_link(hand_over, close)
DIAGRAM.add_link(close, report)
DIAGRAM.add_link(report, ROOT_END_TASK_ID)
