DIAGRAM.set_name('Согласование инвестиционного проекта по реконструкции подстанции')
pool, (initiator, tech, economist, lawyer, committee) = DIAGRAM.add_pool(ROOT_PROCESS_ID, ['Инициатор', 'Тех. эксперт', 'Экономист', 'Юрист', 'Инвестиционный комитет'])
prepare = DIAGRAM.add_user_task('Подготовить паспорт проекта и финансовую модель', initiator)
tech_review = DIAGRAM.add_user_task('Тех. экспертная проверка', tech)
tech_decision = DIAGRAM.add_exclusive_gateway('Тех. эксперт одобрил?', tech)
rev_task = DIAGRAM.add_user_task('Внести замечания', initiator)
econ_review = DIAGRAM.add_user_task('Экономический анализ', economist)
econ_decision = DIAGRAM.add_exclusive_gateway('Экономист одобрил?', economist)
lawyer_task = DIAGRAM.add_user_task('Подготовить заключение по рискам закупки', lawyer)
committee_review = DIAGRAM.add_user_task('Рассмотрение проекта комитетом', committee)
committee_decision = DIAGRAM.add_exclusive_gateway('Включён в инвестпрограмму?', committee)
notify = DIAGRAM.add_user_task('Уведомить инициатора', initiator)
prepare_procurement = DIAGRAM.add_user_task('Начать подготовку к закупке', initiator)
archive = DIAGRAM.add_user_task('Архивировать проект', initiator)
proj_doc = DIAGRAM.add_data_object('Паспорт проекта и финансовая модель', initiator)
risk_report = DIAGRAM.add_data_object('Заключение по рискам закупки', lawyer)
protocol = DIAGRAM.add_data_object('Протокол решения комитета', committee)
DIAGRAM.add_link(ROOT_START_TASK_ID, prepare)
DIAGRAM.add_link(prepare, tech_review)
DIAGRAM.add_link(tech_review, tech_decision)
DIAGRAM.add_link(tech_decision, econ_review, name='да')
DIAGRAM.add_link(tech_decision, rev_task, name='нет')
DIAGRAM.add_link(rev_task, tech_review)
DIAGRAM.add_link(econ_review, econ_decision)
DIAGRAM.add_link(econ_decision, lawyer_task, name='да')
DIAGRAM.add_link(econ_decision, rev_task, name='нет')
DIAGRAM.add_link(lawyer_task, committee_review)
DIAGRAM.add_link(committee_review, committee_decision)
DIAGRAM.add_link(committee_decision, notify, name='да')
DIAGRAM.add_link(committee_decision, archive, name='нет')
DIAGRAM.add_link(notify, prepare_procurement)
DIAGRAM.add_link(prepare_procurement, ROOT_END_TASK_ID)
DIAGRAM.add_link(archive, ROOT_END_TASK_ID)
DIAGRAM.add_link(prepare, proj_doc)
DIAGRAM.add_link(proj_doc, tech_review)
DIAGRAM.add_link(proj_doc, econ_review)
DIAGRAM.add_link(proj_doc, rev_task)
DIAGRAM.add_link(lawyer_task, risk_report)
DIAGRAM.add_link(risk_report, committee_review)
DIAGRAM.add_link(committee_review, protocol)