pool, (initiator, tech, econ, lawyer, committee) = DIAGRAM.add_pool(ROOT_PROCESS_ID, ['Инициатор', 'ТехЭксперт', 'Экономист', 'Юрист', 'Комитет'])
prepare = DIAGRAM.add_user_task('Подготовить паспорт и финансовую модель', initiator)
send = DIAGRAM.add_task('Отправить проект на согласование', initiator)
tech_review = DIAGRAM.add_user_task('ТехЭксперт проверяет проект', tech)
tech_gate = DIAGRAM.add_exclusive_gateway('ТехЭксперт одобрил?', tech)
rev = DIAGRAM.add_user_task('Внести замечания и доработать проект', initiator)
econ_review = DIAGRAM.add_user_task('Экономист оценивает проект', econ)
econ_gate = DIAGRAM.add_exclusive_gateway('Экономист одобрил?', econ)
lawyer_task = DIAGRAM.add_user_task('Подготовить заключение по рискам закупки', lawyer)
committee_task = DIAGRAM.add_user_task('Инвестиционный комитет принимает решение', committee)
committee_gate = DIAGRAM.add_exclusive_gateway('Включить в инвестпрограмму?', committee)
notify = DIAGRAM.add_user_task('Уведомить инициатора', initiator)
proc_prep = DIAGRAM.add_user_task('Начать подготовку к закупке', initiator)
archive = DIAGRAM.add_task('Архивировать проект', initiator)
DIAGRAM.add_link(ROOT_START_TASK_ID, prepare)
DIAGRAM.add_link(prepare, send)
DIAGRAM.add_link(send, tech_review)
DIAGRAM.add_link(tech_review, tech_gate)
DIAGRAM.add_link(tech_gate, econ_review, name='да')
DIAGRAM.add_link(tech_gate, rev, name='нет')
DIAGRAM.add_link(rev, prepare)
DIAGRAM.add_link(econ_review, econ_gate)
DIAGRAM.add_link(econ_gate, lawyer_task, name='да')
DIAGRAM.add_link(econ_gate, rev, name='нет')
DIAGRAM.add_link(lawyer_task, committee_task)
DIAGRAM.add_link(committee_task, committee_gate)
DIAGRAM.add_link(committee_gate, notify, name='да')
DIAGRAM.add_link(committee_gate, archive, name='нет')
DIAGRAM.add_link(notify, proc_prep)
DIAGRAM.add_link(proc_prep, ROOT_END_TASK_ID)
DIAGRAM.add_link(archive, ROOT_END_TASK_ID)
DIAGRAM.set_name('Согласование инвестиционного проекта')