DIAGRAM.set_name('Технологическое присоединение')
pool, (applicant, tc, planning, inspector) = DIAGRAM.add_pool(ROOT_PROCESS_ID, ['Заявитель', 'Специалист по ТП', 'Отдел перспективного развития', 'Инспектор'])

submit = DIAGRAM.add_user_task('Подать заявку', applicant)
plan = DIAGRAM.add_data_object('План расположения ЭПУ', applicant)
check = DIAGRAM.add_user_task('Проверить комплектность', tc)
complete = DIAGRAM.add_exclusive_gateway('Документы комплектны?', tc)
notify = DIAGRAM.add_script_task('Отправить уведомление', tc)
upload = DIAGRAM.add_user_task('Дозагрузить документы', applicant)
register = DIAGRAM.add_script_task('Зарегистрировать заявку', tc)
registry = DIAGRAM.add_data_store('Система учёта заявок', tc)
prepare = DIAGRAM.add_user_task('Подготовить ТУ и проект договора', planning)
contract = DIAGRAM.add_data_object('ТУ и проект договора', planning)
sign = DIAGRAM.add_user_task('Подписать и оплатить договор', applicant)
fork = DIAGRAM.add_parallel_gateway('', planning)
grid_work = DIAGRAM.add_user_task('Выполнить мероприятия сетевой организации', planning)
own_work = DIAGRAM.add_user_task('Выполнить мероприятия заявителя', applicant)
join = DIAGRAM.add_parallel_gateway('', inspector)
inspect = DIAGRAM.add_user_task('Провести осмотр', inspector)
make_act = DIAGRAM.add_user_task('Составить акт о присоединении', inspector)
act = DIAGRAM.add_data_object('Акт о технологическом присоединении', inspector)
sign_act = DIAGRAM.add_user_task('Подписать акт', applicant)

DIAGRAM.add_link(ROOT_START_TASK_ID, submit)
DIAGRAM.add_link(submit, plan)
DIAGRAM.add_link(plan, check)
DIAGRAM.add_link(submit, check)
DIAGRAM.add_link(check, complete)
DIAGRAM.add_link(complete, notify, name='нет')
DIAGRAM.add_link(notify, upload)
DIAGRAM.add_link(upload, check)
DIAGRAM.add_link(complete, register, name='да')
DIAGRAM.add_link(register, registry)
DIAGRAM.add_link(register, prepare)
DIAGRAM.add_link(prepare, contract)
DIAGRAM.add_link(contract, sign)
DIAGRAM.add_link(prepare, sign)
DIAGRAM.add_link(sign, fork)
DIAGRAM.add_link(fork, grid_work)
DIAGRAM.add_link(fork, own_work)
DIAGRAM.add_link(grid_work, join)
DIAGRAM.add_link(own_work, join)
DIAGRAM.add_link(join, inspect)
DIAGRAM.add_link(inspect, make_act)
DIAGRAM.add_link(make_act, act)
DIAGRAM.add_link(make_act, sign_act)
DIAGRAM.add_link(act, sign_act)
DIAGRAM.add_link(sign_act, ROOT_END_TASK_ID)
