DIAGRAM.set_name('Технологическое присоединение к сетям')
pool, (applicant, specialist, dev, org, inspector) = DIAGRAM.add_pool(ROOT_PROCESS_ID, ['Заявитель', 'Специалист по техприсоединению', 'Отдел перспективного развития', 'Сетевая организация', 'Инспектор'])
submit = DIAGRAM.add_user_task('Подать заявку', applicant)
plan_doc = DIAGRAM.add_data_object('План расположения энергопринимающих устройств', applicant)
check = DIAGRAM.add_user_task('Проверить комплектность заявки', specialist)
decision = DIAGRAM.add_exclusive_gateway('Документы полные?', specialist)
notify = DIAGRAM.add_user_task('Отправить уведомление о недостающих документах', specialist)
upload = DIAGRAM.add_user_task('Дозагрузить документы', applicant)
register = DIAGRAM.add_user_task('Зарегистрировать заявку в системе учёта заявок', specialist)
journal = DIAGRAM.add_data_store('Система учёта заявок', specialist)
prepare = DIAGRAM.add_user_task('Подготовить технические условия и проект договора', dev)
tu_doc = DIAGRAM.add_data_object('Технические условия', dev)
contract_doc = DIAGRAM.add_data_object('Проект договора', dev)
send = DIAGRAM.add_user_task('Отправить ТУ и договор заявителю', dev)
sign_contract = DIAGRAM.add_user_task('Подписать договор', applicant)
pay = DIAGRAM.add_user_task('Оплатить услуги', applicant)
split = DIAGRAM.add_parallel_gateway('', org)
org_work = DIAGRAM.add_script_task('Выполнить мероприятия по присоединению', org)
app_work = DIAGRAM.add_user_task('Выполнить свою часть мероприятий', applicant)
join = DIAGRAM.add_parallel_gateway('', org)
inspect = DIAGRAM.add_user_task('Провести осмотр', inspector)
create_act = DIAGRAM.add_user_task('Составить акт об осуществлении технологического присоединения', inspector)
act_doc = DIAGRAM.add_data_object('Акт технологического присоединения', inspector)
sign_act = DIAGRAM.add_user_task('Подписать акт', applicant)
DIAGRAM.add_link(ROOT_START_TASK_ID, submit)
DIAGRAM.add_link(submit, check)
DIAGRAM.add_link(check, decision)
DIAGRAM.add_link(decision, register, name='да')
DIAGRAM.add_link(decision, notify, name='нет')
DIAGRAM.add_link(notify, upload)
DIAGRAM.add_link(upload, check)
DIAGRAM.add_link(register, prepare)
DIAGRAM.add_link(prepare, send)
DIAGRAM.add_link(send, sign_contract)
DIAGRAM.add_link(sign_contract, pay)
DIAGRAM.add_link(pay, split)
DIAGRAM.add_link(split, org_work)
DIAGRAM.add_link(split, app_work)
DIAGRAM.add_link(org_work, join)
DIAGRAM.add_link(app_work, join)
DIAGRAM.add_link(join, inspect)
DIAGRAM.add_link(inspect, create_act)
DIAGRAM.add_link(create_act, sign_act)
DIAGRAM.add_link(sign_act, ROOT_END_TASK_ID)
DIAGRAM.add_link(submit, plan_doc)
DIAGRAM.add_link(plan_doc, check)
DIAGRAM.add_link(register, journal)
DIAGRAM.add_link(send, tu_doc)
DIAGRAM.add_link(send, contract_doc)
DIAGRAM.add_link(tu_doc, sign_contract)
DIAGRAM.add_link(contract_doc, sign_contract)
DIAGRAM.add_link(create_act, act_doc)
DIAGRAM.add_link(act_doc, sign_act)