pool, (applicant, specialist, dept, network, inspector) = DIAGRAM.add_pool(
    ROOT_PROCESS_ID,
    ['Заявитель', 'Специалист по техприсоединению', 'Отдел перспективного развития', 'Сетевая организация', 'Инспектор']
)

submit = DIAGRAM.add_user_task('Подать заявку и план', applicant)
check = DIAGRAM.add_user_task('Проверить комплектность документов', specialist)
gateway = DIAGRAM.add_exclusive_gateway('Документы полные?', specialist)
notify = DIAGRAM.add_script_task('Отправить уведомление о недостающих документах', specialist)
upload = DIAGRAM.add_user_task('Дополнить документы', applicant)
register = DIAGRAM.add_script_task('Зарегистрировать заявку в системе', specialist)
prepare = DIAGRAM.add_user_task('Подготовить ТУ и договор', dept)
send_to_app = DIAGRAM.add_script_task('Отправить ТУ и договор заявителю', dept)
sign_pay = DIAGRAM.add_user_task('Подписать договор и оплатить', applicant)
split = DIAGRAM.add_parallel_gateway('', network)
conn_org = DIAGRAM.add_user_task('Выполнить мероприятия по присоединению', network)
conn_app = DIAGRAM.add_user_task('Выполнить свою часть мероприятий', applicant)
join = DIAGRAM.add_parallel_gateway('', network)
inspect = DIAGRAM.add_user_task('Провести осмотр и составить акт', inspector)
sign_act = DIAGRAM.add_user_task('Подписать акт', applicant)

DIAGRAM.add_link(ROOT_START_TASK_ID, submit)
DIAGRAM.add_link(submit, check)
DIAGRAM.add_link(check, gateway)
DIAGRAM.add_link(gateway, register, name='да')
DIAGRAM.add_link(gateway, notify, name='нет')
DIAGRAM.add_link(notify, upload)
DIAGRAM.add_link(upload, check)
DIAGRAM.add_link(register, prepare)
DIAGRAM.add_link(prepare, send_to_app)
DIAGRAM.add_link(send_to_app, sign_pay)
DIAGRAM.add_link(sign_pay, split)
DIAGRAM.add_link(split, conn_org)
DIAGRAM.add_link(split, conn_app)
DIAGRAM.add_link(conn_org, join)
DIAGRAM.add_link(conn_app, join)
DIAGRAM.add_link(join, inspect)
DIAGRAM.add_link(inspect, sign_act)
DIAGRAM.add_link(sign_act, ROOT_END_TASK_ID)