DIAGRAM.set_name('Передача показаний приборов учёта')
pool, (client, portal, billing_lane, inspector) = DIAGRAM.add_pool(ROOT_PROCESS_ID, ['Абонент', 'Личный кабинет', 'Биллинг', 'Контролёр'])

passed = DIAGRAM.add_exclusive_gateway('Показания переданы до 25 числа?', client)
enter = DIAGRAM.add_user_task('Ввести показания', client)
validate = DIAGRAM.add_script_task('Проверить формат', portal)
save = DIAGRAM.add_script_task('Сохранить показания', portal)
billing = DIAGRAM.add_data_store('Биллинг', billing_lane)
suspicious = DIAGRAM.add_exclusive_gateway('Показания подозрительные?', billing_lane)
visit = DIAGRAM.add_user_task('Выехать к абоненту', inspector)
actual = DIAGRAM.add_user_task('Снять фактические показания', inspector)
act = DIAGRAM.add_user_task('Составить акт проверки', inspector)
act_doc = DIAGRAM.add_data_object('Акт проверки', inspector)
average = DIAGRAM.add_script_task('Начислить по среднему', billing_lane)
merge = DIAGRAM.add_exclusive_gateway('', billing_lane)
bill = DIAGRAM.add_script_task('Сформировать счёт', billing_lane)
deliver = DIAGRAM.add_script_task('Отправить счёт в личный кабинет', portal)

DIAGRAM.add_link(ROOT_START_TASK_ID, passed)
DIAGRAM.add_link(passed, enter, name='да')
DIAGRAM.add_link(passed, average, name='нет')
DIAGRAM.add_link(enter, validate)
DIAGRAM.add_link(validate, save)
DIAGRAM.add_link(save, billing)
DIAGRAM.add_link(save, suspicious)
DIAGRAM.add_link(suspicious, visit, name='да')
DIAGRAM.add_link(suspicious, merge, name='нет')
DIAGRAM.add_link(visit, actual)
DIAGRAM.add_link(actual, act)
DIAGRAM.add_link(act, act_doc)
DIAGRAM.add_link(act_doc, bill)
DIAGRAM.add_link(act, merge)
DIAGRAM.add_link(average, merge)
DIAGRAM.add_link(merge, bill)
DIAGRAM.add_link(billing, bill)
DIAGRAM.add_link(bill, deliver)
DIAGRAM.add_link(deliver, ROOT_END_TASK_ID)
